Feature/projects page
kir-dev/epitesz-klub pull request #24
Opened 2024-12-11 07:48 UTC by DankaMarci

Implemented the projects page component. I also added the events page which appears when you click on a category on the projects page or in the navbar.

2024-12-14 13:23 UTC, balog-b requested changes

2024-12-14 13:23 UTC, balog-b commented on src/app/(app)/projektek/Components/project-groups.tsx
Make a "projects" folder in `/(app)/Components` and move this file there

2024-12-14 13:23 UTC, balog-b commented on src/app/(app)/projektek/Components/category.tsx
Make a "projects" folder in `/(app)/Components` and move this file there, so that we can have all our components in one folder

2024-12-14 13:23 UTC, balog-b commented on src/app/(app)/projektek/[id]/page.tsx
> +    const { id } = params;
Try it with `const { id } = await params;`

https://nextjs.org/docs/messages/sync-dynamic-apis#possible-ways-to-fix-it

2024-12-14 13:23 UTC, balog-b commented on src/app/(app)/Components/navBar/navBar.tsx
> +        <header className="relative w-full" style={{ zIndex: 1000 }}>
Use tailwind: `z-[1000]`

2024-12-14 16:42 UTC, DankaMarci commented
The deployment fails because the vercel database still has the old schema, but when I ran yarn build locally it worked so it should be fine.

2024-12-19 13:57 UTC, balog-b approved these changes

2024-12-19 14:15 UTC, peterlipt approved these changes

2024-12-19 14:15 UTC, merged